

```{r}
NH3_N = c(7.99, 13.28) ; Acetate = c(62.38, 60.72)
tableau1 <- data.frame(x = NH3_N, y = Acetate) 
# Renommer les colonnes
# en reprenant l'exemple ci-dessus
colnames(tableau1) <- c("NH3_N", "Acetate")
# Si le tableau s'appelle data, on peut renommer ses colonnes
data <- colnames(c("nouveau titre","titre nouveau"))

# en reprenant l'exemple ci-dessus
rownames(tableau1) <-c("HY","LY")
```

```{r}
Propionate = c(21.95, 23.14) ; Acetate_propionate_ratio = c(2.85, 2.64)
tableau2 <- data.frame(x = Propionate, y = Acetate_propionate_ratio) 
# Renommer les colonnes
# en reprenant l'exemple ci-dessus
colnames(tableau2) <- c("Propionate", "Acetate_propionate_ratio")
# Si le tableau s'appelle data, on peut renommer ses colonnes
data <- colnames(c("nouveau titre","titre nouveau"))

# en reprenant l'exemple ci-dessus
rownames(tableau2) <-c("HY","LY")
```


```{r}
VFA = c(99.76, 113.63)
tableau3 <- data.frame(x = VFA) 
# Renommer les colonnes
# en reprenant l'exemple ci-dessus
colnames(tableau3) <- c("VFA")
# Si le tableau s'appelle data, on peut renommer ses colonnes
data <- colnames(c("nouveau titre","titre nouveau"))

# en reprenant l'exemple ci-dessus
rownames(tableau3) <-c("HY","LY")
```



```{r}
# en reprenant l'exemple ci-dessus
tableau4 <- cbind(tableau1, tableau2) # Les colonnes du tableau 2 s'ajoutent au tableau 1 pour donner le tableau 3
tableau5 <- cbind(tableau3, tableau4)
```


```{r}
data$NH3_N = as.numeric(data$NH3_N)
data$Acetate = as.numeric(data$Acetate)
data$Propionate= as.numeric(data$Propionate)
data$VFA= as.numeric(data$VFA)
data$Acetate_propionate_ratio= as.numeric(data$Acetate_propionate_ratio)
data = as.matrix(data)

```

```{r}
cormat <- round(cor(tableau5),2)
head(cormat)
```

```{r}
cor(tableau5, method = c("pearson"))
```

# Création d'une heatmap 

```{r}
HY	= c(49.1, 44.33, 0.93, 1.32, 1.07) ; LY	= c(65.61, 27.71, 2.09, 1.57, 0.79)
table1 <- data.frame(x = HY, y = LY) 
# Renommer les colonnes
colnames(table1) <- c("HY","LY")

# 
rownames(table1) <- c("bacteroidetes", "firmicutes", "proteobacteria","tenericutes", "saccharibacteria")
```

```{r}
NH3_N = c(6.75952, 7.392976, 23.016496, 13.104704, 13.137904) ; Acetate = c(30.90648, 33.802824, 22.575304, 59.918496, 60.070296)
HM1 <- data.frame(x = NH3_N, y = Acetate) 
# Renommer les colonnes
colnames(HM1) <- c("NH3_N", "Acetate")
# Renommer les lignes
rownames(HM1) <-c("Bacteroidetes", "Firmicutes", "Proteobacteria", "Tenericutes","Saccharibacteria")
```

```{r}
Propionate = c(11.77826, 12.882038, 22.924798, 22.834552, 22.892402) ; VFA = c(57.83767, 63.257821, 22.083241, 112.130084, 112.414159)
HM2 <- data.frame(x = Propionate, y = VFA) 
# Renommer les colonnes
colnames(HM2) <- c("Propionate", "VFA")
# Renommer les lignes
rownames(HM2) <-c("Bacteroidetes", "Firmicutes", "Proteobacteria", "Tenericutes","Saccharibacteria")
```

```{r}
Ratio = c(1.34376, 1.469688, 2.615448, 2.605152, 2.611752)
HM3 <- data.frame(x = Ratio) 
# Renommer les colonnes
colnames(HM3) <- c("Ratio")
# Renommer les lignes
rownames(HM3) <-c("Bacteroidetes", "Firmicutes", "Proteobacteria", "Tenericutes","Saccharibacteria")
```

```{r}
# en reprenant l'exemple ci-dessus
HM <- cbind(HM1, HM2) # Les colonnes du tableau 2 s'ajoutent au tableau 1 pour donner le tableau 3
HM <- cbind(HM, HM3)
```


```{r}
cormat <- round(cor(HM),2)
head(cormat)
```

```{r}
library(reshape2)
melted_cormat <- melt(cormat)
head(melted_cormat)
```
```{r}
library(ggplot2)
ggplot(data = melted_cormat, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()
```

# Création d'une table phyla 

```{r}
HY = c(49.1, 44.33, 0.93,	1.32, 1.07) ; LY = c(65.61, 27.71, 2.09, 1.57, 0.79)
T_OTU <- data.frame(x = HY, y = LY) 
# Renommer les colonnes
colnames(T_OTU) <- c("HY", "LY")
# Renommer les lignes
rownames(T_OTU) <-c("Bacteroidetes", "Firmicutes", "Proteobacteria", "Tenericutes","Saccharibacteria")
```


# Heatmap V2

```{r}
 library("corrplot")
    D1=HM
    D2=T_OTU
    CorTest=cor(D1, y=D2, use = "everything", method = "pearson")
    CorGraph=corrplot(CorTest, method = "circle", col = colorRampPalette(c("blue","white","red"))(200), title = "Pearson's Correlation of High-Fat Sugar at 12 weeks", tl.cex = .75, tl.col = "Black",diag = TRUE, cl.ratio = 2.25)
```

```{r}
# The mtcars dataset:
dataHM <- as.matrix(HM)
cc = cor(dataHM, method = "pearson")

# Default Heatmap
heatmap(cc)

# Use 'scale' to normalize
heatmap(cc, scale="column")


# No dendrogram nor reordering for neither column or row
heatmap(cc, Colv = NA, Rowv = NA, scale="column")
```
```{r}
library("pheatmap")
pheatmap(HM, scale = "row")
```

```{r}
# Corrélation par paires entre les échantillons (colonnes)
cols.cor <- cor(HM, use = "pairwise.complete.obs", method = "pearson")
# Corrélation par paires entre les lignes (gènes)
rows.cor <- cor(t(HM), use = "pairwise.complete.obs", method = "pearson")

# Créer le heatmap
library("pheatmap")
pheatmap(
  HM, scale = "row", 
  clustering_distance_cols = as.dist(1 - cols.cor),
  clustering_distance_rows = as.dist(1 - rows.cor)
  )
```

## Avec ggplot

```{r}
library("gplots")
heatmap.2(dataHM, scale = "row", col = bluered(100), 
          trace = "none", density.info = "none")
```
```{r}
# Corrélation par paires entre les échantillons (colonnes)
cols.cor <- cor(dataHM, use = "pairwise.complete.obs", method = "pearson")
# Corrélation par paires entre les lignes (gènes)
rows.cor <- cor(t(dataHM), use = "pairwise.complete.obs", method = "pearson")

## Clustering par ligne et par colonne à l'aide d'une corrélation 
hclust.col <- hclust(as.dist(1-cols.cor)) 
hclust.row <- hclust(as.dist(1-rows.cor))


# Créer le heatmap
library("gplots")
heatmap.2(dataHM, scale = "row", col = bluered(100), 
          trace = "none", density.info = "none",
          Colv = as.dendrogram(hclust.col),
          Rowv = as.dendrogram(hclust.row)
          )
```


# Création de tableau pour les genres 

## Pour les "High yields"

```{r}
NH3_N = c(9.410208, 12.32384,	12.258768,	12.720912,	13.217584,	12.80856,	12.694352,	12.833792,	12.925424,	12.865664,	13.0144,	12.893552,	13.031664,	13.099392,	13.023696) ; Acetate = c(43.026192,	56.34816,	56.050632,	58.163688,	60.434616,	58.56444,	58.042248,	58.679808,	59.098776,	58.825536,	59.5056,	58.953048,	59.584536,	59.894208,	59.548104)
Th1 <- data.frame(x = NH3_N, y = Acetate) 
# Renommer les colonnes
colnames(Th1) <- c("NH3_N", "Acetate")
# Renommer les lignes
rownames(Th1) <-c("Prevotella_1", "Ruminococcaceae_NK4A214_group", "Succiniclasticum", "Prevotellaceae", "Prevotella_7", "Bacteroidales_S24_7_group", "Ruminococcus_2", "Bacteroidales_BS11", "Rikenellaceae_RC9_gut_group", "Christensenellaceae_R_7_group", "Prevotellaceae_UCG_003", "Lachnospiraceae_NK3A20_group", "Ruminococcaceae_UCG_014", "Prevotellaceae_UCG_001",
 "Eubacterium_coprostanoligenes_group")
```

```{r}
Propionate = c(16.397004,	21.47392,	21.360534,	22.165806,	23.031242,	22.31853,	22.119526,	22.362496,	22.522162,	22.418032,	22.6772,	22.466626,	22.707282,	22.825296,	22.693398) ; VFA = c(80.518218,	105.44864,	104.891853,	108.846177,	113.095939,	109.596135,	108.618917,	109.812032,	110.596079,	110.084744,	111.3574,	110.323367,	111.505119,	112.084632,	111.436941)
Th2 <- data.frame(x = Propionate, y = VFA) 
# Renommer les colonnes
colnames(Th2) <- c("Propionate", "VFA")
# Renommer les lignes
rownames(Th2) <-c("Prevotella_1", "Ruminococcaceae_NK4A214_group", "Succiniclasticum", "Prevotellaceae", "Prevotella_7", "Bacteroidales_S24_7_group", "Ruminococcus_2", "Bacteroidales_BS11", "Rikenellaceae_RC9_gut_group", "Christensenellaceae_R_7_group", "Prevotellaceae_UCG_003", "Lachnospiraceae_NK3A20_group", "Ruminococcaceae_UCG_014", "Prevotellaceae_UCG_001",
 "Eubacterium_coprostanoligenes_group")
```

```{r}
Ratio_Acetate_Propionate = c(1.870704,	2.44992,	2.436984,	2.528856,	2.627592,	2.54628,	2.523576,	2.551296,	2.569512,	2.557632,	2.5872,	2.563176,	2.590632,	2.604096,	2.589048)
Th3 <- data.frame(x = Ratio_Acetate_Propionate) 
# Renommer les colonnes
colnames(Th3) <- c("Ratio_Acetate_Propionate")
# Renommer les lignes
rownames(Th3) <-c("Prevotella_1", "Ruminococcaceae_NK4A214_group", "Succiniclasticum", "Prevotellaceae", "Prevotella_7", "Bacteroidales_S24_7_group", "Ruminococcus_2", "Bacteroidales_BS11", "Rikenellaceae_RC9_gut_group", "Christensenellaceae_R_7_group", "Prevotellaceae_UCG_003", "Lachnospiraceae_NK3A20_group", "Ruminococcaceae_UCG_014", "Prevotellaceae_UCG_001",
 "Eubacterium_coprostanoligenes_group")
```

```{r}
# Réunification des tables
Table_gen_HY <- cbind(Th1, Th2) # Les colonnes du tableau 2 s'ajoutent au tableau 1 pour donner le tableau 3
Table_gen_HY <- cbind(Table_gen_HY, Th3)
```

## Pour les "low yields"

```{r}
NH3_N = c(4.120208,	7.03384,	6.968768,	7.430912,	7.927584,	7.51856,	7.404352,	7.543792,	7.635424,	7.575664,	7.7244,	7.603552,	7.741664,	7.809392,	7.733696) ; Acetate = c(58.510208,	61.42384,	61.358768,	61.820912,	62.317584,	61.90856,	61.794352,	61.933792,	62.025424,	61.965664,	62.1144,	61.993552,	62.131664,	62.199392,	62.123696)
Tl1 <- data.frame(x = NH3_N, y = Acetate) 
# Renommer les colonnes
colnames(Tl1) <- c("NH3_N", "Acetate")
# Renommer les lignes
rownames(Tl1) <-c("Prevotella_1", "Ruminococcaceae_NK4A214_group", "Succiniclasticum", "Prevotellaceae", "Prevotella_7", "Bacteroidales_S24_7_group", "Ruminococcus_2", "Bacteroidales_BS11", "Rikenellaceae_RC9_gut_group", "Christensenellaceae_R_7_group", "Prevotellaceae_UCG_003", "Lachnospiraceae_NK3A20_group", "Ruminococcaceae_UCG_014", "Prevotellaceae_UCG_001",
 "Eubacterium_coprostanoligenes_group")
```

```{r}
Propionate = c(18.080208,	20.99384,	20.928768,	21.390912,	21.887584,	21.47856,	21.364352,	21.503792,	21.595424,	21.535664,	21.6844,	21.563552,	21.701664,	21.769392,	21.693696) ; VFA = c(95.890208,	98.80384,	98.738768,	99.200912,	99.697584,	99.28856,	99.174352,	99.313792,	99.405424,	99.345664,	99.4944,	99.373552,	99.511664,	99.579392,	99.503696)
Tl2 <- data.frame(x = Propionate, y = VFA) 
# Renommer les colonnes
colnames(Tl2) <- c("Propionate", "VFA")
# Renommer les lignes
rownames(Tl2) <-c("Prevotella_1", "Ruminococcaceae_NK4A214_group", "Succiniclasticum", "Prevotellaceae", "Prevotella_7", "Bacteroidales_S24_7_group", "Ruminococcus_2", "Bacteroidales_BS11", "Rikenellaceae_RC9_gut_group", "Christensenellaceae_R_7_group", "Prevotellaceae_UCG_003", "Lachnospiraceae_NK3A20_group", "Ruminococcaceae_UCG_014", "Prevotellaceae_UCG_001",
 "Eubacterium_coprostanoligenes_group")
```

```{r}
Ratio_Acetate_Propionate = c(-1.019792,	1.89384,	1.828768,	2.290912,	2.787584,	2.37856,	2.264352,	2.403792,	2.495424,	2.435664,	2.5844,	2.463552,	2.601664,	2.669392,	2.593696)
Tl3 <- data.frame(x = Ratio_Acetate_Propionate) 
# Renommer les colonnes
colnames(Tl3) <- c("Ratio_Acetate_Propionate")
# Renommer les lignes
rownames(Tl3) <-c("Prevotella_1", "Ruminococcaceae_NK4A214_group", "Succiniclasticum", "Prevotellaceae", "Prevotella_7", "Bacteroidales_S24_7_group", "Ruminococcus_2", "Bacteroidales_BS11", "Rikenellaceae_RC9_gut_group", "Christensenellaceae_R_7_group", "Prevotellaceae_UCG_003", "Lachnospiraceae_NK3A20_group", "Ruminococcaceae_UCG_014", "Prevotellaceae_UCG_001",
 "Eubacterium_coprostanoligenes_group")
```

```{r}
# Réunification des tables
Table_gen_LY <- cbind(Tl1, Tl2) # Les colonnes du tableau 2 s'ajoutent au tableau 1 pour donner le tableau 3
Table_gen_LY <- cbind(Table_gen_LY, Tl3)
```


# Construction des heatmap 

## Pour les high yields

```{r}
Tab <- round(cor(Table_gen_HY),2)
head(cormat)
```

```{r}
# Default Heatmap
heatmap(dataHL)

# Use 'scale' to normalize
heatmap(dataHL, scale="column")


# No dendrogram nor reordering for neither column or row
heatmap(dataHL, Colv = NA, Rowv = NA, scale="column")
```



### Avec pheatmap
```{r}
# Mettre en data.frame
dataHL <- as.matrix(Table_gen_HY)
```

```{r}
library("pheatmap")
pheatmap(Table_gen_HY, scale = "row")
```

```{r}
# Corrélation par paires entre les échantillons (colonnes)
cols.cor <- cor(Table_gen_HY, use = "pairwise.complete.obs", method = "pearson")
# Corrélation par paires entre les lignes (gènes)
rows.cor <- cor(t(Table_gen_HY), use = "pairwise.complete.obs", method = "pearson")

# Créer le heatmap
library("pheatmap")
pheatmap(
  Table_gen_HY, scale = "row", 
  clustering_distance_cols = as.dist(1 - cols.cor),
  clustering_distance_rows = as.dist(1 - rows.cor)
  )
```

### Avec ggplot

```{r}
library("gplots")
heatmap.2(dataHL, scale = "row", col = bluered(100), 
          trace = "none", density.info = "none")
```

```{r}
# Corrélation par paires entre les échantillons (colonnes)
cols.cor <- cor(dataHL, use = "pairwise.complete.obs", method = "pearson")
# Corrélation par paires entre les lignes (gènes)
rows.cor <- cor(t(dataHL), use = "pairwise.complete.obs", method = "pearson")

## Clustering par ligne et par colonne à l'aide d'une corrélation 
hclust.col <- hclust(as.dist(1-cols.cor)) 
hclust.row <- hclust(as.dist(1-rows.cor))


# Créer le heatmap
library("gplots")
heatmap.2(dataHL, scale = "row", col = bluered(100), 
          trace = "none", density.info = "none",
          Colv = as.dendrogram(hclust.col),
          Rowv = as.dendrogram(hclust.row)
          )
```


```{r}
 library("corrplot")
    D1=Table_gen_LY
    D2=Table_gen_HY
    CorTest=cor(D1, y=D2, use = "everything", method = "pearson")
    CorGraph=corrplot(CorTest, method = "circle", col = colorRampPalette(c("blue","white","red"))(200), title = "Pearson's Correlation of High-Fat Sugar at 12 weeks", tl.cex = .75, tl.col = "Black",diag = TRUE, cl.ratio = 2.25)
```

```{r}
df <- scale(Table_gen_HY)
```
```{r}
heatmap(df, scale = "row", method = "pearson")
```

```{r}
head(Table_gen_HY)
```
```{r}
cor(Table_gen_HY)
```


```{r}
library(ggpubr)

my_data <- Table_gen_HY
my_data$NH3_N <- factor(my_data$NH3_N)
str(my_data)
```

```{r}
ggscatter(my_data, x = "Propionate", y = "Acetate",
          add = "reg.line", conf.int = TRUE,
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Weight (1000 lbs)", ylab = "Miles/ (US) gallon")
```

```{r}
res <- cor.test(my_data$Propionate, my_data$Acetate, method = "pearson")
res
```

```{r}
str(res)
```
```{r}
res$p.value
```

```{r}
res$estimate
```


# Création d'un table pour l'abondance relative des genres

```{r}
HY = c(29.14, 7.20, 7.69, 4.21, 0.47, 3.55, 4.41, 3.36, 2.67, 3.12, 2.00, 2.91, 1.87, 1.36, 1.93) ; LY = c(37.48, 4.12, 3.57, 5.96, 8.41, 3.44, 1.36, 2.21, 2.87, 2.00, 2.20, 1.18, 1.99, 1.55, 0.80)
Table_ar_gen <- data.frame(x = HY, y = LY) 
# Renommer les colonnes
colnames(Table_ar_gen) <- c("HY", "LY")
# Renommer les lignes
rownames(Table_ar_gen) <-c("Prevotella_1", "Ruminococcaceae_NK4A214_group", "Succiniclasticum", "Prevotellaceae", "Prevotella_7", "Bacteroidales_S24_7_group", "Ruminococcus_2", "Bacteroidales_BS11", "Rikenellaceae_RC9_gut_group", "Christensenellaceae_R_7_group", "Prevotellaceae_UCG_003", "Lachnospiraceae_NK3A20_group", "Ruminococcaceae_UCG_014", "Prevotellaceae_UCG_001",
 "Eubacterium_coprostanoligenes_group")
```

# Test de student 
```{r}
par(mar=c(5,20,1,2))
barplot(t(Table_ar_gen),beside=T,ylim=c(0,50), xlim=c(0,40), xlab="Genre",axis.lty="solid",horiz=T, las=1, col=c(" dark green","dark orange"), legend=TRUE, xpd = FALSE)

```
## Intervale de confiance 

```{r}
# prevotella 1
x_prev1<-c(29.14, 37.48)
# test de student pour échantillon unique
res_prev1<-t.test(x_prev1, mu=0)
res_prev1 # Affichage du résultat du test 
```
```{r}
# Ruminococcaceae_NK4A214_group
x2<-c(7.20, 4.12)
# test de student pour échantillon unique
res2<-t.test(x2, mu=0)
res2 # Affichage du résultat du test 
```

```{r}
# Succiniclasticum
x3<-c(7.69, 3.57)
# test de student pour échantillon unique
res3<-t.test(x3, mu=0)
res3 # Affichage du résultat du test 
```
```{r}
# Prevotellaceae
x4<-c(4.21, 5.96)
# test de student pour échantillon unique
res4<-t.test(x4, mu=0)
res4 # Affichage du résultat du test 
```

```{r}
# Prevotella_7
x5<-c(0.47,8.41)
# test de student pour échantillon unique
res5<-t.test(x5, mu=0)
res5 # Affichage du résultat du test 
```

```{r}
# Bacteroidales_S24_7_group
x6<-c(3.55,3.44)
# test de student pour échantillon unique
res6<-t.test(x6, mu=0)
res6 # Affichage du résultat du test 
```

```{r}
# Ruminococcus_2
x7<-c(4.41,1.36)
# test de student pour échantillon unique
res7<-t.test(x7, mu=0)
res7 # Affichage du résultat du test 
```


```{r}
# Bacteroidales_BS11
x8<-c(3.36,2.21)
# test de student pour échantillon unique
res8<-t.test(x8, mu=0)
res8 # Affichage du résultat du test 
```

```{r}
# Rikenellaceae_RC9_gut_group
x9<-c(2.67,2.87)
# test de student pour échantillon unique
res9<-t.test(x9, mu=0)
res9 # Affichage du résultat du test 
```

```{r}
# Christensenellaceae_R_7_group
x10<-c(3.12,2.00)
# test de student pour échantillon unique
res10<-t.test(x10, mu=0)
res10 # Affichage du résultat du test 
```

```{r}
# Prevotellaceae_UCG_003
x11<-c(2.00,2.20)
# test de student pour échantillon unique
res11<-t.test(x11, mu=0)
res11 # Affichage du résultat du test 
```

```{r}
# Lachnospiraceae_NK3A20_group
x12<-c(2.91,1.18)
# test de student pour échantillon unique
res12<-t.test(x12, mu=0)
res12 # Affichage du résultat du test 
```


```{r}
# Ruminococcaceae_UCG_014
x13<-c(1.87,1.99)
# test de student pour échantillon unique
res13<-t.test(x13, mu=0)
res13 # Affichage du résultat du test 
```

```{r}
# Prevotellaceae_UCG_001
x14<-c(1.36,1.55)
# test de student pour échantillon unique
res14<-t.test(x14, mu=0)
res14 # Affichage du résultat du test 
```

```{r}
# Eubacterium_coprostanoligenes_group
x15<-c(1.93,0.80)
# test de student pour échantillon unique
res15<-t.test(x15, mu=0)
res15 # Affichage du résultat du test 
```


```{r}
p_value = c(0.07928, 0.1691, 0.2233, 0.1085, 0.4645, 0.01002, 0.3096, 0.1296, 0.02297, 0.1371, 0.03029, 0.2548, 0.01978, 0.04151, 0.2498)
Table_pvalue <- data.frame(x = p_value) 
# Renommer les colonnes
colnames(Table_pvalue) <- c("p_value")
# Renommer les lignes
rownames(Table_pvalue) <-c("Prevotella_1", "Ruminococcaceae_NK4A214_group", "Succiniclasticum", "Prevotellaceae", "Prevotella_7", "Bacteroidales_S24_7_group", "Ruminococcus_2", "Bacteroidales_BS11", "Rikenellaceae_RC9_gut_group", "Christensenellaceae_R_7_group", "Prevotellaceae_UCG_003", "Lachnospiraceae_NK3A20_group", "Ruminococcaceae_UCG_014", "Prevotellaceae_UCG_001",
 "Eubacterium_coprostanoligenes_group")
```

### Les différences de proportion

```{r}
DIFF = c(-8.34,3.08,4.12,-1.75,-7.94,0.11,3.05,1.15,-0.2,1.12,-0.2,1.73,-0.12,-0.19,1.13) 
diff<- data.frame(x = DIFF) 
# Renommer les colonnes
colnames(diff) <- c("DIFF")
# Renommer les lignes
rownames(diff) <-c("0.07928", "0.1691", "0.2233", "0.1085", "0.4645", "0.01002", "0.3096", "0.1296", "0.02297", "0.1371", "0.03029", "0.2548", "0.01978", "0.04151", "0.2498")
```

```{r}
vec <- c(-8.34,3.08,4.12,-1.75,-7.94,0.11,3.05,1.15,-0.2,1.12,-0.2,1.73,-0.12,-0.19,1.13)
```

```{r}
se = sd(vec) / sqrt(length(vec))
```


```{r}
alpha=0.05
t=qt((1-alpha)/2 + .5, length(vec)-1)   # tend to 1.96 if sample size is big enough
CI=t*se
```

```{r}
Diffpval <- cbind(Table_pvalue, DIFF)
```



```{r}
ggplot(Diffpval) +
  geom_bar( aes(x=p_value, y=DIFF), stat="identity", fill="blue", alpha=1) +
  geom_errorbar( aes(x=p_value, ymin=DIFF-CI, ymax=DIFF+CI), width=0.4, colour="orange", alpha=0.3, size=1) +
  ggtitle("using confidence interval")
```

```{r}
df <- data.frame(x =1:15,
                 Prevotella_1 =runif(10,-19.67487, 86.29487),
                 Ruminococcaceae_NK4A214_group =runif(10,-13.90756, 25.22756),
                 Succiniclasticum =runif(10,-20.54478  31.80478),
                 Prevotellaceae =runif(10, -6.032929 16.202929),
                 Prevotella_7 =runif(10, -46.00363  54.88363),
                 Bacteroidales_S24_7_group =runif(10, 2.796159 4.193841),
                 Ruminococcus_2 =runif(10, 2.796159 4.193841),
                 Bacteroidales_BS11
                 Rikenellaceae_RC9_gut_group
                 Christensenellaceae_R_7_group
                 Prevotellaceae_UCG_003
                 Lachnospiraceae_NK3A20_group
                 Ruminococcaceae_UCG_014
                 Prevotellaceae_UCG_001
                 Eubacterium_coprostanoligenes_group)

require(ggplot2)
ggplot(df, aes(x = x, y = F)) +
  geom_point(size = 4) +
  geom_errorbar(aes(ymax = U, ymin = L))
```

```{r}
library(plotrix)

y <- runif(15)
err <- runif(10)
plotCI(1:10, y, err, main = "Basic plotCI")
```

```{r}
plotCI (x= DIFF, y = NULL, uiw =10, liw = -25, ui = NULL, li = NULL, err = "y",
  sfrac = 0.01, gap = 0, slty = par ("lty"), add = FALSE, scol = NULL, pt.bg = par ("bg"))

```

```{r}
 y <-DIFF
 err <-runif (15)
 plotCI (DIFF, y, err, main = "Basic plotCI")
 plotCI (DIFF, y, err, 2 * err, lwd = 2, col = "red", scol = "blue",
  main = "Ajouter des couleurs aux points et aux barres d'erreur")
 err.x <-runif (15)
 err.y <-runif (15)
 plotCI (DIFF, y, err.y, pt.bg = par ("bg"), pch = 21, xlim = c (0,11),
  main = "plotCI avec espace supplémentaire sur l'axe x")
 plotCI (DIFF, y, err.x, pt.bg = par ("bg"), pch = 21, err = "x", add = TRUE)
 mtext ("pour ajouter des barres d'erreur horizontales", 3,0.5)

```


```{r}
plotmeans(DIFF ~ p_value, data = diff, frame = FALSE,
          mean.labels = FALSE, connect = FALSE, p=0.95, bars=TRUE,
          ci.label=FALSE, n.label=TRUE, text.n.label="n=",
          digits=getOption("digits"), col="black", barwidth=1,
          barcol="blue", ccol=
          col, use.t=TRUE,
          lwd=par("lwd"))
```
```{r}
# Load ggplot2
library(ggplot2)
data <- data.frame(
  name=c("0.07928", "0.1691", "0.2233", "0.1085", "0.4645", "0.01002", "0.3096", "0.1296", "0.02297", "0.1371", "0.03029", "0.2548", "0.01978", "0.04151", "0.2498"),
  value=c(-8.34,3.08,4.12,-1.75,-7.94,0.11,3.05,1.15,-0.2,1.12,-0.2,1.73,-0.12,-0.19,1.13),
  sd=c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0))
 
# Most basic error bar
ggplot(data) +
    geom_bar( aes(x=name, y=value), stat="identity", fill="skyblue", alpha=0.7) +
    geom_errorbar( aes(x=name, ymin=value-sd, ymax=value+sd), width=0.4, colour="orange", alpha=0.95, size=1)
```

```{r}
ggplot(Diffpval) +
  geom_bar( aes(x=p_value, y=DIFF), stat="identity", fill="forestgreen", alpha=0.5) +
  geom_errorbar( aes(x=p_value, ymin=DIFF-CI, ymax=DIFF+CI), width=0.4, colour="orange", alpha=0.9, size=1.5) +
  ggtitle("using confidence interval")
```







